### PR TITLE
Interpolate color according to progress percentage.

### PR DESCRIPTION
**Pull request by manuyavuz**
This interpolates bar color with the following red-yellow-green pattern .

| progress | red component | green component |
| --- | --- | --- |
| 0 | maxRed | minGreen |
| 50 | maxRed | maxGreen |
| 100 | minRed | maxGreen |

Thanks for the great plugin!

### CODE REVIEW

**Comment by manuyavuz** [comment]
I think we can move yellow percent from %50 to ranges around %75 in order to encourge developers to improve coverage, what do you think?

**Comment by zats** [comment]
hey @manuyavuz, thanks a lot for PR! I like the idea of raising the threshold, however I wanted to keep the colours the way they are now – the original idea of the plugin is to provide quick understanding of your current state without looking at the details.
Thanks though! :cake:

**Comment by manuyavuz** [comment]
Hey @zats, thanks for the response!

I actually thought about your possible reasoning behind your current implementation before I made the PR, but I still wanted to make this change and hear what you think. While I was using the plugin, I had to look for percent coverage values carefully in order to find out which yellow/red classes are actually better/acceptable comparing to others. And I personally always find visual differences more descriptive.

I put here two comparison: 

| default | interpolate |
| --- | --- |
| screen shot 2015-12-03 at 11 05 25 | screen shot 2015-12-03 at 11 35 46 |

If this feels too unsteady, what about differentiating yellow and red tones a little according to coverage percent? This way, we both can preserve warning developers for any not %100 covered classes, still put a hard threshold around %70 to encourage them improve coverage, and also can differentiate visually. Are you OK with this?

Again, thanks for the great job! Seeing these color always pushes me to make them green 😁

**Comment by zats** [comment]
Visually your version looks very good indeed! 
You got it right, my reasoning behind original version though is that I want a clear differentiation between "bad" "acceptable" and "great". 
I don't mind having gradual mode as an additional option, however I have no framework in place to store selected preferences and such :disappointed: 
I adopted your suggestions regarding 70% threshold though! :bow:

**Comment by manuyavuz** [comment]
Fair.  Putting the plugin simple is important, it should not have a prefs screen only for such a change. Also I can poke you again if plugin has a pref page anytime :)

Closing this for now.

**Comment by zats** [comment]
Thanks for understanding 🙌

**Pull request closed without merging**
